# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Knt"
license = "MIT"
licenselink = "https://github.com/kushal124/knt-hugo-theme/blob/master/LICENSE.md"
description = ""
homepage = "http://kushal124.github.io/knt-hugo-theme"
tags = ["knt", "hugo", "minimalistic", "blacknwhite"]
features = ["", ""]
min_version = 0.15

[author]
  name = "Kushal Khandelwal"
  homepage = "http://kushalkhandelwal.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
